[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "12"
  NODE_OPTIONS = "--max_old_space_size=4096"

[build]
  publish = "dist"
  command = "npm i && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
